# Makefile for PuTTY under cygwin.
#
# Extra options you can set:
#
#  - FWHACK=-DFWHACK
#      Enables a hack that tunnels through some firewall proxies.
#
#  - VER=-DSNAPSHOT=1999-01-25
#      Generates executables whose About box report them as being a
#      development snapshot.
#
#  - VER=-DRELEASE=0.43
#      Generates executables whose About box report them as being a
#      release version.
#
#  - COMPAT=-DAUTO_WINSOCK
#      Causes PuTTY to assume that <windows.h> includes its own WinSock
#      header file, so that it won't try to include <winsock.h>.
#
#  - COMPAT=-DWINSOCK_TWO
#      Causes the PuTTY utilities to include <winsock2.h> instead of
#      <winsock.h>, except Plink which _needs_ WinSock 2 so it already
#      does this.
#
#  - COMPAT=-DNO_SECURITY
#      Disables Pageant's use of <aclapi.h>, which is not available
#      with some development environments. This means that Pageant
#      won't care about the local user ID of processes accessing it; a
#      version of Pageant built with this option will therefore refuse
#      to run under NT-series OSes on security grounds (although it
#      will run fine on Win95-series OSes where there is no access
#      control anyway).
#
#      Note that this definition is always enabled in the Cygwin
#      build, since at the time of writing this <aclapi.h> is known
#      not to be available in Cygwin.
#
#  - COMPAT=-DNO_MULTIMON
#      Disables PuTTY's use of <multimon.h>, which is not available
#      with some development environments. This means that PuTTY's
#      full-screen mode (configurable to work on Alt-Enter) will
#      not behave usefully in a multi-monitor environment.
#
#  - COMPAT=-DMSVC4
#  - RCFL=-DMSVC4
#      Makes a couple of minor changes so that PuTTY compiles using
#      MSVC 4. You will also need /DNO_SECURITY and /DNO_MULTIMON.
#
#  - RCFL=-DASCIICTLS
#      Uses ASCII rather than Unicode to specify the tab control in
#      the resource file. Probably most useful when compiling with
#      Cygnus/mingw32, whose resource compiler may have less of a
#      problem with it.
#
#  - XFLAGS=-DDEBUG
#      Causes PuTTY to enable internal debugging.
#
#  - XFLAGS=-DMALLOC_LOG
#      Causes PuTTY to emit a file called putty_mem.log, logging every
#      memory allocation and free, so you can track memory leaks.
#
#  - XFLAGS=-DMINEFIELD
#      Causes PuTTY to use a custom memory allocator, similar in
#      concept to Electric Fence, in place of regular malloc(). Wastes
#      huge amounts of RAM, but should cause heap-corruption bugs to
#      show up as GPFs at the point of failure rather than appearing
#      later on as second-level damage.
#

# You can define this path to point at your tools if you need to
# TOOLPATH = c:\cygwin\bin\ # or similar, if you're running Windows
# TOOLPATH = /pkg/mingw32msvc/i386-mingw32msvc/bin/
CC = $(TOOLPATH)gcc
RC = $(TOOLPATH)windres
# You may also need to tell windres where to find include files:
# RCINC = --include-dir c:\cygwin\include\

CFLAGS = -mno-cygwin -Wall -O2 -D_WINDOWS -DDEBUG -DWIN32S_COMPAT -DNO_SECURITY -D_NO_OLDNAMES -I.
LDFLAGS = -mno-cygwin -s
RCFLAGS = $(RCINC) --define WIN32=1 --define _WIN32=1 --define WINVER=0x0400 --define MINGW32_FIX=1
LIBS = -ladvapi32 -luser32 -lgdi32 -lwsock32 -lcomctl32 -lcomdlg32 -lwinmm -limm32
OBJ=o
RES=res.o

GOBJS1 = window.$(OBJ) windlg.$(OBJ) winctrls.$(OBJ) terminal.$(OBJ)
GOBJS2 = sizetip.$(OBJ) wcwidth.$(OBJ) unicode.$(OBJ) logging.$(OBJ)
LOBJS1 = telnet.$(OBJ) raw.$(OBJ) rlogin.$(OBJ) ldisc.$(OBJ) winnet.$(OBJ)
POBJS = be_all.$(OBJ)
TOBJS = be_nossh.$(OBJ)
PLOBJS = plink.$(OBJ) logging.$(OBJ)
SOBJS = scp.$(OBJ) winnet.$(OBJ) be_none.$(OBJ) wildcard.$(OBJ)
FOBJS = psftp.$(OBJ) winnet.$(OBJ) be_none.$(OBJ)
SFOBJS = sftp.$(OBJ) int64.$(OBJ) logging.$(OBJ)
MOBJS = misc.$(OBJ) version.$(OBJ) winstore.$(OBJ) settings.$(OBJ)
MOBJ2 = tree234.$(OBJ)
COBJS = console.$(OBJ)
OBJS1 = sshcrc.$(OBJ) sshdes.$(OBJ) sshmd5.$(OBJ) sshrsa.$(OBJ) sshrand.$(OBJ)
OBJS2 = sshsha.$(OBJ) sshblowf.$(OBJ) noise.$(OBJ) sshdh.$(OBJ) sshcrcda.$(OBJ)
OBJS3 = sshpubk.$(OBJ) ssh.$(OBJ) pageantc.$(OBJ) sshzlib.$(OBJ) sshdss.$(OBJ)
OBJS4 = x11fwd.$(OBJ) portfwd.$(OBJ) sshaes.$(OBJ) sshsh512.$(OBJ) sshbn.$(OBJ)
PAGE1 = pageant.$(OBJ) sshrsa.$(OBJ) sshpubk.$(OBJ) sshdes.$(OBJ) sshbn.$(OBJ)
PAGE2 = sshmd5.$(OBJ) version.$(OBJ) tree234.$(OBJ) misc.$(OBJ) sshaes.$(OBJ)
PAGE3 = sshsha.$(OBJ) pageantc.$(OBJ) sshdss.$(OBJ) sshsh512.$(OBJ)
GEN1 = puttygen.$(OBJ) sshrsag.$(OBJ) sshdssg.$(OBJ) sshprime.$(OBJ)
GEN2 = sshdes.$(OBJ) sshbn.$(OBJ) sshmd5.$(OBJ) version.$(OBJ) sshrand.$(OBJ)
GEN3 = noise.$(OBJ) sshsha.$(OBJ) winstore.$(OBJ) misc.$(OBJ) winctrls.$(OBJ)
GEN4 = sshrsa.$(OBJ) sshdss.$(OBJ) sshpubk.$(OBJ) sshaes.$(OBJ) sshsh512.$(OBJ)
PRESRC = win_res.$(RES)
PAGERC = pageant.$(RES)
GENRC = puttygen.$(RES)
SRESRC = scp.$(RES)
LRESRC = plink.$(RES)

.SUFFIXES:

%.o: %.c
	$(CC) $(COMPAT) $(FWHACK) $(XFLAGS) $(CFLAGS) -c $<

%.res.o: %.rc
	$(RC) $(FWHACK) $(RCFL) $(RCFLAGS) $< $@

all: puttygen.exe pageant.exe puttytel.exe psftp.exe pscp.exe plink.exe putty.exe

puttygen.exe: $(GEN1) $(GEN2) $(GEN3) $(GEN4) $(GENRC)
	$(CC) -mwindows $(LDFLAGS) -o $@ $(GEN1) $(GEN2) $(GEN3) $(GEN4) $(GENRC) $(LIBS)

pageant.exe: $(PAGE1) $(PAGE2) $(PAGE3) $(PAGERC)
	$(CC) -mwindows $(LDFLAGS) -o $@ $(PAGE1) $(PAGE2) $(PAGE3) $(PAGERC) $(LIBS)

puttytel.exe: $(GOBJS1) $(GOBJS2) $(LOBJS1) $(TOBJS) $(MOBJS) $(MOBJ2) $(PRESRC)
	$(CC) -mwindows $(LDFLAGS) -o $@ $(GOBJS1) $(GOBJS2) $(LOBJS1) $(TOBJS) $(MOBJS) $(MOBJ2) $(PRESRC) $(LIBS)

psftp.exe: $(FOBJS) $(SFOBJS) $(MOBJS) $(MOBJ2) $(COBJS) $(OBJS1) $(OBJS2) $(OBJS3) $(OBJS4) $(SRESRC)
	$(CC) $(LDFLAGS) -o $@ $(FOBJS) $(SFOBJS) $(MOBJS) $(MOBJ2) $(COBJS) $(OBJS1) $(OBJS2) $(OBJS3) $(OBJS4) $(SRESRC) $(LIBS)

pscp.exe: $(SOBJS) $(SFOBJS) $(MOBJS) $(MOBJ2) $(COBJS) $(OBJS1) $(OBJS2) $(OBJS3) $(OBJS4) $(SRESRC)
	$(CC) $(LDFLAGS) -o $@ $(SOBJS) $(SFOBJS) $(MOBJS) $(MOBJ2) $(COBJS) $(OBJS1) $(OBJS2) $(OBJS3) $(OBJS4) $(SRESRC) $(LIBS)

plink.exe: $(LOBJS1) $(POBJS) $(PLOBJS) $(MOBJS) $(MOBJ2) $(COBJS) $(OBJS1) $(OBJS2) $(OBJS3) $(OBJS4) $(LRESRC)
	$(CC) $(LDFLAGS) -o $@ $(LOBJS1) $(POBJS) $(PLOBJS) $(MOBJS) $(MOBJ2) $(COBJS) $(OBJS1) $(OBJS2) $(OBJS3) $(OBJS4) $(LRESRC) $(LIBS) -lws2_32

putty.exe: $(GOBJS1) $(GOBJS2) $(LOBJS1) $(POBJS) $(MOBJS) $(MOBJ2) $(OBJS1) $(OBJS2) $(OBJS3) $(OBJS4) $(PRESRC)
	$(CC) -mwindows $(LDFLAGS) -o $@ $(GOBJS1) $(GOBJS2) $(LOBJS1) $(POBJS) $(MOBJS) $(MOBJ2) $(OBJS1) $(OBJS2) $(OBJS3) $(OBJS4) $(PRESRC) $(LIBS)

be_all.$(OBJ): be_all.c network.h misc.h puttymem.h putty.h 
be_none.$(OBJ): be_none.c network.h misc.h puttymem.h putty.h 
be_nossh.$(OBJ): be_nossh.c network.h misc.h puttymem.h putty.h 
ber.$(OBJ): ber.c network.h asn.h misc.h asnerror.h int64.h puttymem.h ssh.h putty.h 
cert.$(OBJ): cert.c asn.h asnerror.h misc.h puttymem.h cert.h crypto.h 
debug.$(OBJ): debug.c debug.h 
int64.$(OBJ): int64.c int64.h 
ldisc.$(OBJ): ldisc.c network.h misc.h puttymem.h putty.h 
misc.$(OBJ): misc.c network.h misc.h puttymem.h putty.h 
mscrypto.$(OBJ): mscrypto.c network.h int64.h puttymem.h ssh.h 
no_ssl.$(OBJ): no_ssl.c network.h misc.h puttymem.h putty.h 
noise.$(OBJ): noise.c network.h misc.h puttymem.h storage.h int64.h ssh.h putty.h 
pageant.$(OBJ): pageant.c network.h int64.h puttymem.h ssh.h tree234.h 
pageantc.$(OBJ): pageantc.c puttymem.h 
plink.$(OBJ): plink.c network.h misc.h puttymem.h storage.h putty.h tree234.h 
portfwd.$(OBJ): portfwd.c network.h misc.h int64.h puttymem.h ssh.h putty.h 
psftp.$(OBJ): psftp.c network.h misc.h sftp.h ssh.h storage.h int64.h puttymem.h putty.h 
puttygen.$(OBJ): puttygen.c network.h misc.h int64.h puttymem.h winstuff.h ssh.h putty.h 
raw.$(OBJ): raw.c network.h misc.h puttymem.h putty.h 
rlogin.$(OBJ): rlogin.c network.h misc.h puttymem.h putty.h 
scp.$(OBJ): scp.c network.h misc.h sftp.h ssh.h storage.h puttymem.h int64.h putty.h winstuff.h 
settings.$(OBJ): settings.c network.h misc.h puttymem.h storage.h putty.h 
sftp.$(OBJ): sftp.c sftp.h int64.h 
sizetip.$(OBJ): sizetip.c network.h misc.h puttymem.h winstuff.h putty.h 
ssh.$(OBJ): ssh.c network.h misc.h int64.h puttymem.h ssh.h putty.h tree234.h 
sshaes.$(OBJ): sshaes.c network.h int64.h puttymem.h ssh.h 
sshblowf.$(OBJ): sshblowf.c network.h int64.h puttymem.h ssh.h 
sshbn.$(OBJ): sshbn.c network.h misc.h int64.h puttymem.h ssh.h putty.h 
sshcrc.$(OBJ): sshcrc.c 
sshdes.$(OBJ): sshdes.c network.h int64.h puttymem.h ssh.h 
sshdh.$(OBJ): sshdh.c network.h int64.h puttymem.h ssh.h 
sshdss.$(OBJ): sshdss.c network.h misc.h int64.h puttymem.h ssh.h 
sshdssg.$(OBJ): sshdssg.c network.h misc.h int64.h puttymem.h ssh.h 
sshmd5.$(OBJ): sshmd5.c network.h int64.h puttymem.h ssh.h 
sshprime.$(OBJ): sshprime.c network.h int64.h puttymem.h ssh.h 
sshpubk.$(OBJ): sshpubk.c network.h int64.h puttymem.h ssh.h 
sshrand.$(OBJ): sshrand.c network.h int64.h puttymem.h ssh.h 
sshrsa.$(OBJ): sshrsa.c network.h int64.h puttymem.h ssh.h 
sshrsag.$(OBJ): sshrsag.c network.h int64.h puttymem.h ssh.h 
sshsh512.$(OBJ): sshsh512.c network.h int64.h puttymem.h ssh.h 
sshsha.$(OBJ): sshsha.c network.h int64.h puttymem.h ssh.h 
sshzlib.$(OBJ): sshzlib.c network.h int64.h puttymem.h ssh.h 
ssl.$(OBJ): ssl.c network.h asnerror.h misc.h cert.h crypto.h ssl.h int64.h puttymem.h 
telnet.$(OBJ): telnet.c network.h misc.h puttymem.h putty.h 
terminal.$(OBJ): terminal.c network.h misc.h puttymem.h putty.h tree234.h 
logging.$(OBJ): logging.c misc.h puttymem.h putty.h
test.$(OBJ): test.c network.h int64.h puttymem.h ssh.h 
tree234.$(OBJ): tree234.c tree234.h 
unicode.$(OBJ): unicode.c network.h misc.h puttymem.h putty.h 
version.$(OBJ): version.c 
wcwidth.$(OBJ): wcwidth.c 
wildcard.$(OBJ): wildcard.c 
winctrls.$(OBJ): winctrls.c network.h misc.h puttymem.h putty.h winstuff.h 
windlg.$(OBJ): windlg.c network.h misc.h ssh.h storage.h puttymem.h int64.h putty.h winstuff.h win_res.h 
window.$(OBJ): window.c network.h misc.h puttymem.h storage.h winstuff.h putty.h win_res.h 
winnet.$(OBJ): winnet.c network.h misc.h puttymem.h putty.h tree234.h 
winstore.$(OBJ): winstore.c network.h misc.h puttymem.h storage.h putty.h 
x11fwd.$(OBJ): x11fwd.c network.h misc.h int64.h puttymem.h ssh.h putty.h 
win_res.$(RES): win_res.rc win_res.h putty.ico
scp.$(RES): scp.rc scp.ico
pageant.$(RES): pageant.rc pageant.ico pageants.ico
puttygen.$(RES): puttygen.rc puttygen.ico

version.o: FORCE;
# Hack to force version.o to be rebuilt always
FORCE:
	$(CC) $(FWHACK) $(CFLAGS) $(VER) -c version.c

clean:
	rm -f *.o *.exe *.res

